name: SnykContainer

on:
  push: 
   branches:
      - main
  pull_request: 
   types: [ labeled, opened, reopened, synchronize ]

permissions:
  contents: read
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Calculate metadata
      id: meta
      if: ${{ github.event.pull_request.merged }} 
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ github.event.pull_request.head.sha }}
          
    - name: Set env
      if: ${{ github.event.pull_request.merged }} 
      run: echo "GITHUB_PR_SHA=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
      
    - name: Test
      if: ${{ github.event.pull_request.merged }} 
      run: echo $GITHUB_PR_SHA
    
    - name: Build a Docker image
      run: docker build -t your/image-to-test .
    
    - name: Run Snyk to check Docker image for vulnerabilities
      id: snyk
      continue-on-error: true
      uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: your/image-to-test
        args: --file=Dockerfile
              --severity-threshold=medium
    
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
    
    - name: Check on failures
      if: steps.snyk.outcome != 'success'
      run: exit 1
